/*
GMO Coin APIs

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: dev@tricoro.tech
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// OrderbooksDataAsks struct for OrderbooksDataAsks
type OrderbooksDataAsks struct {
	Price *int32 `json:"price,omitempty"`
	Size *int32 `json:"size,omitempty"`
}

// NewOrderbooksDataAsks instantiates a new OrderbooksDataAsks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderbooksDataAsks() *OrderbooksDataAsks {
	this := OrderbooksDataAsks{}
	return &this
}

// NewOrderbooksDataAsksWithDefaults instantiates a new OrderbooksDataAsks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderbooksDataAsksWithDefaults() *OrderbooksDataAsks {
	this := OrderbooksDataAsks{}
	return &this
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *OrderbooksDataAsks) GetPrice() int32 {
	if o == nil || o.Price == nil {
		var ret int32
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderbooksDataAsks) GetPriceOk() (*int32, bool) {
	if o == nil || o.Price == nil {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *OrderbooksDataAsks) HasPrice() bool {
	if o != nil && o.Price != nil {
		return true
	}

	return false
}

// SetPrice gets a reference to the given int32 and assigns it to the Price field.
func (o *OrderbooksDataAsks) SetPrice(v int32) {
	o.Price = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *OrderbooksDataAsks) GetSize() int32 {
	if o == nil || o.Size == nil {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderbooksDataAsks) GetSizeOk() (*int32, bool) {
	if o == nil || o.Size == nil {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *OrderbooksDataAsks) HasSize() bool {
	if o != nil && o.Size != nil {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *OrderbooksDataAsks) SetSize(v int32) {
	o.Size = &v
}

func (o OrderbooksDataAsks) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Price != nil {
		toSerialize["price"] = o.Price
	}
	if o.Size != nil {
		toSerialize["size"] = o.Size
	}
	return json.Marshal(toSerialize)
}

type NullableOrderbooksDataAsks struct {
	value *OrderbooksDataAsks
	isSet bool
}

func (v NullableOrderbooksDataAsks) Get() *OrderbooksDataAsks {
	return v.value
}

func (v *NullableOrderbooksDataAsks) Set(val *OrderbooksDataAsks) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderbooksDataAsks) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderbooksDataAsks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderbooksDataAsks(val *OrderbooksDataAsks) *NullableOrderbooksDataAsks {
	return &NullableOrderbooksDataAsks{value: val, isSet: true}
}

func (v NullableOrderbooksDataAsks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderbooksDataAsks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


