/*
GMO Coin APIs

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: dev@tricoro.tech
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AccountMarginData struct for AccountMarginData
type AccountMarginData struct {
	ActualProfitLoss *string `json:"actualProfitLoss,omitempty"`
	AvailableAmount *string `json:"availableAmount,omitempty"`
	Margin *string `json:"margin,omitempty"`
	MarginCallStatus *string `json:"marginCallStatus,omitempty"`
	MarginRatio *string `json:"marginRatio,omitempty"`
	ProfitLoss *string `json:"profitLoss,omitempty"`
}

// NewAccountMarginData instantiates a new AccountMarginData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountMarginData() *AccountMarginData {
	this := AccountMarginData{}
	return &this
}

// NewAccountMarginDataWithDefaults instantiates a new AccountMarginData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountMarginDataWithDefaults() *AccountMarginData {
	this := AccountMarginData{}
	return &this
}

// GetActualProfitLoss returns the ActualProfitLoss field value if set, zero value otherwise.
func (o *AccountMarginData) GetActualProfitLoss() string {
	if o == nil || o.ActualProfitLoss == nil {
		var ret string
		return ret
	}
	return *o.ActualProfitLoss
}

// GetActualProfitLossOk returns a tuple with the ActualProfitLoss field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountMarginData) GetActualProfitLossOk() (*string, bool) {
	if o == nil || o.ActualProfitLoss == nil {
		return nil, false
	}
	return o.ActualProfitLoss, true
}

// HasActualProfitLoss returns a boolean if a field has been set.
func (o *AccountMarginData) HasActualProfitLoss() bool {
	if o != nil && o.ActualProfitLoss != nil {
		return true
	}

	return false
}

// SetActualProfitLoss gets a reference to the given string and assigns it to the ActualProfitLoss field.
func (o *AccountMarginData) SetActualProfitLoss(v string) {
	o.ActualProfitLoss = &v
}

// GetAvailableAmount returns the AvailableAmount field value if set, zero value otherwise.
func (o *AccountMarginData) GetAvailableAmount() string {
	if o == nil || o.AvailableAmount == nil {
		var ret string
		return ret
	}
	return *o.AvailableAmount
}

// GetAvailableAmountOk returns a tuple with the AvailableAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountMarginData) GetAvailableAmountOk() (*string, bool) {
	if o == nil || o.AvailableAmount == nil {
		return nil, false
	}
	return o.AvailableAmount, true
}

// HasAvailableAmount returns a boolean if a field has been set.
func (o *AccountMarginData) HasAvailableAmount() bool {
	if o != nil && o.AvailableAmount != nil {
		return true
	}

	return false
}

// SetAvailableAmount gets a reference to the given string and assigns it to the AvailableAmount field.
func (o *AccountMarginData) SetAvailableAmount(v string) {
	o.AvailableAmount = &v
}

// GetMargin returns the Margin field value if set, zero value otherwise.
func (o *AccountMarginData) GetMargin() string {
	if o == nil || o.Margin == nil {
		var ret string
		return ret
	}
	return *o.Margin
}

// GetMarginOk returns a tuple with the Margin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountMarginData) GetMarginOk() (*string, bool) {
	if o == nil || o.Margin == nil {
		return nil, false
	}
	return o.Margin, true
}

// HasMargin returns a boolean if a field has been set.
func (o *AccountMarginData) HasMargin() bool {
	if o != nil && o.Margin != nil {
		return true
	}

	return false
}

// SetMargin gets a reference to the given string and assigns it to the Margin field.
func (o *AccountMarginData) SetMargin(v string) {
	o.Margin = &v
}

// GetMarginCallStatus returns the MarginCallStatus field value if set, zero value otherwise.
func (o *AccountMarginData) GetMarginCallStatus() string {
	if o == nil || o.MarginCallStatus == nil {
		var ret string
		return ret
	}
	return *o.MarginCallStatus
}

// GetMarginCallStatusOk returns a tuple with the MarginCallStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountMarginData) GetMarginCallStatusOk() (*string, bool) {
	if o == nil || o.MarginCallStatus == nil {
		return nil, false
	}
	return o.MarginCallStatus, true
}

// HasMarginCallStatus returns a boolean if a field has been set.
func (o *AccountMarginData) HasMarginCallStatus() bool {
	if o != nil && o.MarginCallStatus != nil {
		return true
	}

	return false
}

// SetMarginCallStatus gets a reference to the given string and assigns it to the MarginCallStatus field.
func (o *AccountMarginData) SetMarginCallStatus(v string) {
	o.MarginCallStatus = &v
}

// GetMarginRatio returns the MarginRatio field value if set, zero value otherwise.
func (o *AccountMarginData) GetMarginRatio() string {
	if o == nil || o.MarginRatio == nil {
		var ret string
		return ret
	}
	return *o.MarginRatio
}

// GetMarginRatioOk returns a tuple with the MarginRatio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountMarginData) GetMarginRatioOk() (*string, bool) {
	if o == nil || o.MarginRatio == nil {
		return nil, false
	}
	return o.MarginRatio, true
}

// HasMarginRatio returns a boolean if a field has been set.
func (o *AccountMarginData) HasMarginRatio() bool {
	if o != nil && o.MarginRatio != nil {
		return true
	}

	return false
}

// SetMarginRatio gets a reference to the given string and assigns it to the MarginRatio field.
func (o *AccountMarginData) SetMarginRatio(v string) {
	o.MarginRatio = &v
}

// GetProfitLoss returns the ProfitLoss field value if set, zero value otherwise.
func (o *AccountMarginData) GetProfitLoss() string {
	if o == nil || o.ProfitLoss == nil {
		var ret string
		return ret
	}
	return *o.ProfitLoss
}

// GetProfitLossOk returns a tuple with the ProfitLoss field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountMarginData) GetProfitLossOk() (*string, bool) {
	if o == nil || o.ProfitLoss == nil {
		return nil, false
	}
	return o.ProfitLoss, true
}

// HasProfitLoss returns a boolean if a field has been set.
func (o *AccountMarginData) HasProfitLoss() bool {
	if o != nil && o.ProfitLoss != nil {
		return true
	}

	return false
}

// SetProfitLoss gets a reference to the given string and assigns it to the ProfitLoss field.
func (o *AccountMarginData) SetProfitLoss(v string) {
	o.ProfitLoss = &v
}

func (o AccountMarginData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ActualProfitLoss != nil {
		toSerialize["actualProfitLoss"] = o.ActualProfitLoss
	}
	if o.AvailableAmount != nil {
		toSerialize["availableAmount"] = o.AvailableAmount
	}
	if o.Margin != nil {
		toSerialize["margin"] = o.Margin
	}
	if o.MarginCallStatus != nil {
		toSerialize["marginCallStatus"] = o.MarginCallStatus
	}
	if o.MarginRatio != nil {
		toSerialize["marginRatio"] = o.MarginRatio
	}
	if o.ProfitLoss != nil {
		toSerialize["profitLoss"] = o.ProfitLoss
	}
	return json.Marshal(toSerialize)
}

type NullableAccountMarginData struct {
	value *AccountMarginData
	isSet bool
}

func (v NullableAccountMarginData) Get() *AccountMarginData {
	return v.value
}

func (v *NullableAccountMarginData) Set(val *AccountMarginData) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountMarginData) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountMarginData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountMarginData(val *AccountMarginData) *NullableAccountMarginData {
	return &NullableAccountMarginData{value: val, isSet: true}
}

func (v NullableAccountMarginData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountMarginData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


