name: Deploy Swagger UI Pages & Generate Client Lib

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - "api/openapi-spec/**"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run:  ls -l
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: api/openapi-spec/openapi.yaml
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui
      - name: Generate client library for GMO Coin
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: go
          openapi-file: api/openapi-spec/openapi.yaml
          command-args: -o client --additional-properties=packageName=client
      - name: Commit generated files
        run: |
          git config --local user.email "y16ra@users.noreply.github.com"
          git config --local user.name "y16ra"
          git add client
          git commit -m "Update client" -a
          git pull
          git push
